name: Sync from RooVetGit/Roo-Code into auto-sync branch

permissions:
  contents: write    # Needed to push the branch

on:
  schedule:
    - cron: '0 2 * * *'  # Every day at 2 AM UTC
  workflow_dispatch:     # Allow manual trigger

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Set up Git config
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Add upstream remote
        run: |
          git remote add upstream https://github.com/RooVetGit/Roo-Code.git
          git fetch upstream

      - name: Create or update auto-sync branch
        run: |
          git checkout -B auto-sync
          git merge upstream/main --allow-unrelated-histories --no-edit

      - name: Push auto-sync branch
        run: |
          git push origin auto-sync --force
